### ISSUE TITLE
SHA256 mismatch on perforce

### ISSUE THREAD

**Issue by jrep** [Homebrew/homebrew-binary#182]
>% brew upgrade 
...
==> Upgrading perforce
==> Downloading http://filehost.perforce.com/perforce/r14.2/bin.macosx105x86_64/p4
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: ce0e80f29813159a0384fafb77d85590e57e2d3deea3a42ad55ee9b70c842002
Actual: 0d2ad21ecc03493a9b429907fb49209369ca09fd87340c03812dc1d1748dc562
Archive: /Library/Caches/Homebrew/perforce-2014.2.962050
To retry an incomplete download, remove the file above.

Retry no help.
I did run `brew update` immediately prior.
The "Downloading" file (blah blah/p4) is of the expected type (Mach-O 64-bit executable x86_64).

OS X 10.10.1 (14B25)

**Comment by DevByStarlight** [comment]
Appears to be outdated once again...

brew install perforce
==> Installing perforce from homebrew/homebrew-binary
==> Downloading http://filehost.perforce.com/perforce/r15.1/bin.macosx105x86_64/p4
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 21a87b9e44577a0530359a47e77725e097fb10b22a2eaf0beb8f9ebb099a65b8
Actual: 121609310da778f4910ba2f8502d46372900859a1059ebe53224eab6194b1ba5
Archive: /Library/Caches/Homebrew/perforce-2015.1.1024208
To retry an incomplete download, remove the file above.
