### ISSUE TITLE
SHA256 mismatch for perforce

### ISSUE THREAD

**Issue by piefra** [Homebrew/homebrew-binary#211]
==> Installing perforce from homebrew/homebrew-binary
==> Downloading http://filehost.perforce.com/perforce/r14.2/bin.macosx105x86_64/p4
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 0d2ad21ecc03493a9b429907fb49209369ca09fd87340c03812dc1d1748dc562
Actual: c1f920a244f53907a6edfa7fe9d6472ecafffc17e026d9165a2a6e6c65a0ef72
Archive: /Library/Caches/Homebrew/perforce-2014.2.978861
To retry an incomplete download, remove the file above.

**Comment by uncreative** [comment]
same issue for me.
