### ISSUE TITLE
Dead url for lmutil

### ISSUE THREAD

**Issue by kinyobi** [Homebrew/homebrew-binary#215]
Looks like the url below is now dead and the recipe for lmutil is equally dead. I have not found a publicly available alternative at this point.

$ brew info lmutil
lmutil: stable 11.11
http://www.globes.com/support/fnp_utilities_download.htm
Not installed

$ brew install lmutil
==> Installing lmutil from homebrew/homebrew-binary
==> Downloading http://www.globes.com/products/utilities/v11.11/lmutil_universal_mac10.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "lmutil"
Download failed: http://www.globes.com/products/utilities/v11.11/lmutil_universal_mac10.tar.gz

**Comment by mistydemeo** [comment]
> must contact the publisher

is pretty definitive, hm. I'll remove the formula.
