### ISSUE TITLE
adobe-air-sdk SHA256 mismatch

### ISSUE THREAD

**Issue by ydesgagn** [Homebrew/homebrew-binary#240]
==> Installing adobe-air-sdk from homebrew/homebrew-binary
==> Downloading http://airdownload.adobe.com/air/mac/download/17.0/AIRSDK_Compiler.tbz2
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 7fe1b5172fd4b2144751dace46b3335eededc28398ae4672db9fab4b1ab6c634
Actual: 36643ae1349ffde5e48a52ab37186460e1a5eb6051589e6e2004f6c1f865f3db
Archive: /Library/Caches/Homebrew/adobe-air-sdk-17.0.0.144.tbz2

**Comment by levithomason** [comment]
Followed other similar issue posts here.  My error:

```console
› brew cask install pepper-flash                         
==> Downloading https://admdownload.adobe.com/bin/live/AdobeFlashPlayer_18ppau_a
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 7422df27c7b372d402bc1c88291f4e6fb5a1b1c0c3274b3b902cddf9f2dea046
Actual: 55fc94580f301fb51d75b5fa1121a83c4a2b3c2a6c5b81c3ea640f777eb27945
File: /Library/Caches/Homebrew/pepper-flash-18.0.0.203.dmg
To retry an incomplete download, remove the file above.

› brew doctor
Your system is ready to brew.
```

Note, brew update did not fix it.

**Comment by bfontaine** [comment]
@levithomason this is an error with [Homebrew-Cask](https://github.com/caskroom/homebrew-cask).

**Comment by levithomason** [comment]
Ok, thanks. Will post over there.

**Comment by dunn** [comment]
This happened because http://airdownload.adobe.com/air/mac/download/17.0/AIRSDK_Compiler.tbz2 just points to the latest 17.0.x release, and it's been updated.  

18.0 is also out now.  Would you be willing to submit a pull request to update the formula?  😺

**Comment by L2G** [comment]
I'm already working on this formula.
