### ISSUE TITLE
SHA256 mismatch on little-cms2

### ISSUE THREAD

**Issue by swave** [Homebrew/homebrew-binary#246]
==> Upgrading little-cms2
==> Downloading https://downloads.sourceforge.net/project/lcms/lcm
==> Downloading from http://downloads.sourceforge.net/#!/project/l
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 4524234ae7de185e6b6da5d31d6875085b2198bc63b1211f7dde6e2d197d6a53
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821

**Comment by DomT4** [comment]
See https://github.com/Homebrew/homebrew/issues/41778.
