### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by chrisburgin95** [Homebrew/homebrew-binary#247]
MongoDB

Expected: 8a8993e1914801ace5ce83c92bf4c43127669750e9dec8eb93574e57729e9c42
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
Archive: /Library/Caches/Homebrew/scons-2.3.5.tar.gz
To retry an incomplete download, remove the file above.

brew update did not fix

**Comment by dunn** [comment]
SourceForge is still having a lot of problems (https://github.com/Homebrew/homebrew/issues/41778); unfortunately this is just something we have to wait for them to fix.
