### ISSUE TITLE
Sha256 mismatch on air-sdk and air-sdk-flex

### ISSUE THREAD

**Issue by midorikocak** [Homebrew/homebrew-binary#265]
$ brew install homebrew/binary/adobe-air-sdk-flex
==> Installing adobe-air-sdk-flex from homebrew/homebrew-binary
==> Downloading http://airdownload.adobe.com/air/mac/download/18.0/AdobeAIRSDK.t
Already downloaded: /Library/Caches/Homebrew/adobe-air-sdk-flex-18.0.0.180.tbz2
Error: SHA256 mismatch
Expected: e431348a81e99c8d07b1b42b4b35895f202ad9df53a5cb1f08b3461c5bed16d4
Actual: 6ce96ce97f2a88ccbc06838f30c743c81e05eb8ab0a82216a1da45cbe30f626e
Archive: /Library/Caches/Homebrew/adobe-air-sdk-flex-18.0.0.180.tbz2
To retry an incomplete download, remove the file above.

**Comment by DomT4** [comment]
The download links are relatively static and break when Adobe pushes an update upstream, which has happened here. If you'd like you could file a PR with the updated checksum & version; that'd be really appreciated.
