### ISSUE TITLE
sha mismatch for perforce

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-binary#269]
```
~$ brew install perforce
==> Installing perforce from homebrew/homebrew-binary
==> Downloading http://filehost.perforce.com/perforce/r15.1/bin.macosx105x86_64/p4
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: a6d39a35f2be437e2fcbc28a5d0a6b520a584bc122a262c8a5f14cf1dd1811c9
Actual: 32a4b1da589ce70d408772268986bf9bd09aa22f30c8883cf5cf47eeff8f73ae
Archive: /Library/Caches/Homebrew/perforce-2015.1.1227227
```

**Comment by dunn** [comment]
Yeah, looks like it's just been changed: http://filehost.perforce.com/perforce/r15.1/

These aren't properly versioned binaries (we use the date as the version string), so when they're updated the SHA doesn't match and it needs to be updated as well to match.  Interested in opening a pull request?

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew-binary/commit/e0ce8dc363942179345b192b1603310de42ee7f4.
