### ISSUE TITLE
Formula for PNGOUT

### ISSUE THREAD

**Issue by timsutton** [Homebrew/homebrew-binary#286]
I have a formula for an OS X binary port of PNGOUT here:

https://gist.github.com/timsutton/1cbced5d19c0ba6cd44a

It's free but source is not available, with the original author's license here:

http://advsys.net/ken/utils.htm#pngoutkziplicense

Would this formula be suitable for homebrew-binary? If so, I can open a PR based on this Gist.

Thanks!

**Comment by mistydemeo** [comment]
There were previous requests for this in #73 and #53; when the author was contacted, his business partner requested that it not be included here. Sorry!

**Comment by timsutton** [comment]
Oops, sorry - I should have checked this repo's previous issues. Thanks for the quick response!
