### ISSUE TITLE
brew install homebrew/binary/subgit doesn't work out of the box

### ISSUE THREAD

**Issue by msiebuhr** [Homebrew/homebrew-binary#310]
Installing subgit doesn't seem to work out the box:

    > brew install homebrew/binary/subgit
    ...
    ==> Caveats
        To use SubGit, you must agree to the SubGit licensing agreement:
          http://subgit.com/license.html
    ==> Summary
    🍺  /usr/local/Cellar/subgit/3.0.0: 37 files, 12.8M, built in 1 second
    >rehash
    >subgit
    Error: JAVA_HOME is not defined correctly.
      We cannot execute /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/bin/java
    >/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/bin/java
    zsh: no such file or directory: /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/bin/java

(I'm guessing a dependency on a JVM is missing somewhere.)

**Comment by msiebuhr** [comment]
I could get things started with

    > brew install java
    > JAVACMD=/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java subgit

Some readme's mention that doing a reboot or re-login might fix the latter part, but I haven't given it a shot yet.

**Comment by dunn** [comment]
Does this also happen if you download and install subgit outside of Homebrew?

**Comment by msiebuhr** [comment]
Nope.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
