### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by yzhzu** [Homebrew/homebrew-binary#350]
brew install tbl2asn
==> Installing tbl2asn from homebrew/science
==> Downloading ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters
Already downloaded: /home/rcmm/.cache/Homebrew/tbl2asn-24.9.gz
Error: SHA256 mismatch
Expected: 730d9bcf6d654e2395d19e529f01a4f670030633129ceea2dbf6e4850e42aa2a
Actual: 0f95c6c2872b2beb908eb42a64b15ed282424332faab3c442b43fc8b99548e58
Archive: /home/rcmm/.cache/Homebrew/tbl2asn-24.9.gz
To retry an incomplete download, remove the file above.

can someone tell me how to sovle this problem? thank you very much

**Comment by ilovezfs** [comment]
I fixed it for you in https://github.com/Homebrew/homebrew-science/pull/4052, which I'll push when :green_apple:

**Comment by ilovezfs** [comment]
It's now fixed if you `brew update`.
