### ISSUE TITLE
rar is not available in casks

### ISSUE THREAD

**Issue by JosephEarl** [Homebrew/homebrew-binary#369]
Attempting to install `binary/rar` results in the following:

```
Warning: Use caskroom/cask/rar instead of deprecated homebrew/binary/rar
Error: No available formula with the name "caskroom/cask/rar" 
```

I think the user should be pointed either at `unrar` or at `caskroom/cask/unrarx`.

**Comment by ilovezfs** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/rar.rb

brew cask install rar

**Comment by MikeMcQuaid** [comment]
This repository is deprecated.
